#!/bin/bash
uv run python domino/gen.py
uv run python domino/gen_linear.py
uv run python domino/gen_spiral.py
uv run python domino/gen_11tower.py
uv run python domino/gen_speedwall.py
uv run python domino/gen_pyramid.py
uv run python domino/gen_doublehelix.py
uv run python domino/gen_castle.py
uv run python domino/gen_zigzag_tower.py
uv run python domino/gen_spiral_tower.py
uv run python domino/gen_colosseum.py
uv run python domino/gen_basketweave.py
uv run python domino/gen_cascade.py
uv run python domino/gen_fanwall.py
uv run python domino/gen_zigzagwall.py
uv run python domino/gen_spiralwall.py
uv run python domino/gen_dualpeaks.py
uv run python domino/gen_heart.py
uv run python domino/gen_star.py
uv run python domino/gen_lissajous.py
uv run python domino/gen_stairs.py
uv run python domino/gen_maze.py
uv run python domino/gen_bounce.py
uv run python domino/gen_flower.py
uv run python domino/gen_tree.py
uv run python domino/gen_snake.py
uv run python domino/gen_gear.py
uv run python domino/gen_wavegrid.py
uv run python domino/gen_arch.py
uv run python domino/gen_blackhole.py
uv run python domino/gen_mandala.py
uv run python domino/gen_rollercoaster.py
uv run python domino/gen_city.py
uv run python domino/gen_dragon.py
